### ISSUE TITLE
Provide Case STL files

### ISSUE THREAD

**Issue by heynest** [kumekay/crabapplepad#5]
### User Story
**As a** re-creator
**I want to** download STL files for the case
**So that** I do not need to by a Fusion license (which costs at least 96 €)

Currently, I cannot "just" print the case but I need to get fusion first (as far as I see).

**Comment by kumekay** [comment]
Hello @heynest 

Thank you for the interest 

I don't have my laptop with me, but you can use Fusion for free https://www.autodesk.com/products/fusion-360/personal


BTW, I'm planning a new iteration of the keyboard this summer with a few flaws fixed (but it will be a bit thicker)

**Comment by heynest** [comment]
Thanks for your quick reaction and the hint for autodesk!

Well, actually, I do not want to rebuild it as you may think. I like the idea of having a foldable and expandablre base to which I can mount my ZSA Voyager (magnetically) when I need to go to a meeting room...
I wanted to have the STL files to understand how you built the mechanism...

Thanks for sharing.

**Comment by kumekay** [comment]
It's a simple hinge with a thin steel wire inside:

![image](https://github.com/kumekay/crabapplepad/assets/2738/d776c7ab-ef69-4e46-90ed-7dd8386f424d)



STLs: [Archive.zip](https://github.com/kumekay/crabapplepad/files/15061328/Archive.zip)
